"""user model

Revision ID: 0f27616c468d
Revises: 40acc1503054
Create Date: 2016-05-28 13:10:41.641432

"""

# revision identifiers, used by Alembic.
revision = '0f27616c468d'
down_revision = '40acc1503054'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
