"""initial migration

Revision ID: 40acc1503054
Revises: None
Create Date: 2016-05-27 18:00:37.886195

"""

# revision identifiers, used by Alembic.
revision = '40acc1503054'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
